# Generated by Django 2.0.3 on 2018-04-11 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of the user',
                        max_length=128
                    )
                ),
                (
                    'location',
                    models.CharField(
                        help_text='Location of the user',
                        max_length=128
                    )
                ),
                (
                    'silph_card',
                    models.CharField(
                        help_text="URL of User's Silph Card",
                        max_length=128
                    )
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
    ]
