# Generated by Django 2.0.3 on 2018-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of the Pokemon',
                        max_length=128
                    )
                ),
                (
                    'dex_number',
                    models.SmallIntegerField(
                        help_text='Number of the Pokemon in the Pokedex'
                    )
                ),
            ],
        ),
    ]
