# Generated by Django 2.0.5 on 2018-05-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='featured_image', to='api.Image'),
        ),
    ]
