# Generated by Django 2.0.3 on 2018-04-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('url', models.URLField()),
                (
                    'pokemon',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='api.Pokemon'
                    )
                ),
                (
                    'profile',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='api.Profile'
                    )
                ),
            ],
        ),
    ]
