# Generated by Django 2.0.3 on 2018-04-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Image')),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Pokemon')),
            ],
        ),
    ]
