# Generated by Django 2.0.4 on 2018-04-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pokedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Pokemon'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile'),
        ),
    ]
