# Generated by Django 2.0.4 on 2018-04-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180427_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexentry',
            name='image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='api.Image'
            ),
        ),
        migrations.AlterField(
            model_name='pokedexentry',
            name='pokemon',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='api.Pokemon'
            ),
        ),
    ]
