# Generated by Django 2.0.7 on 2018-09-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180925_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='api.Image'
                )),
            ],
        ),
        migrations.RemoveField(
            model_name='pokedexentry',
            name='image',
        ),
        migrations.AlterField(
            model_name='collection',
            name='entries',
            field=models.ManyToManyField(blank=True, to='api.CollectionEntry'),
        ),
        migrations.DeleteModel(
            name='PokedexEntry',
        ),
    ]
