# Generated by Django 2.0.7 on 2018-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180925_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(
                choices=[('pokedex', 'Pokedex'), ('album', 'Album')],
                default='pokedex',
                max_length=12
            ),
        ),
    ]
